rootNode:

    requiredPlugin: {SofaPython , SoftRobots, ModelOrderReduction}
    visualStyle: showCollision showVisualModels showForceFields showInteractionForceFields hideCollisionModels hideBoundingCollisionModels hideWireframe    
    sceneParam:

        dt: 1
        gravity: 0 0 -9810

solverNode: 

    GenericConstraintCorrection:
        solverName: SparseLDLSolver

## note : don't put name inside Param -> will not find the component anymore
modelNode:

    pathTodir: 1_INPUT/Mesh_Model/
    nameModelMesh: siliconeV0.vtu
    nameModelVisu: surface.stl
    actuatorConfigFile: 1_INPUT/Configuration_Files/config_Diamond_Actuators.yml
    rotation: 90 0 0
    translation: 0 0 35
    
    totalmass: 0.5
    
    BoxROIpts: -15 -15 -40  15 15 10

    BoxROI: 

        FixedConstraint:
            indices: '@BoxROI.indices'


    ForceField:

        TetrahedronFEMForceField:
            youngModulus: 450
            poissonRatio: 0.45

    pythonControllers: 
    -   filename : 1_INPUT/Python_Controllers/shakeModel.py
        classname : interface
