rootNode:

    requiredPlugin: {SofaPython , SoftRobots, ModelOrderReduction}
    visualStyle: showVisualModels showBehaviorModels hideCollisionModels hideBoundingCollisionModels showForceFields showInteractionForceFields hideWireframe    
    sceneParam:
        
        gravity: 0 0 -9810

    collision: 

        bool: true
        friction: mu=0.7

## note : don't put name inside Param -> will not find the component anymore
modelNode:

    pathTodir: 1_INPUT/Mesh_Model/
    nameModelMesh: full_quadriped_SMALL.vtk
    nameModelVisu: quadriped_collision.stl
    nameModelCol: quadriped_collision.stl
    actuatorConfigFile: 1_INPUT/Configuration_Files/config_Starfish_Actuator.yml

    totalmass: 0.200

    BoxROIpts: 0 0 -0.1 150 -100 0.1
    SubTopo : True
    BoxROI: 

        TriangleSetTopologyContainer:

            position: '@loader.position' 
            triangles: '@BoxROI.trianglesInROI'

        TriangleFEMForceField:

            method: large
            poissonRatio: 0.49
            youngModulus: 5000

    ForceField :

        TetrahedronFEMForceField:
            method: large
            youngModulus: 70
            poissonRatio: 0.05
            drawAsEdges: 1

    linearSolver: ../SparseLDLSolver
    
    pythonControllers: 
    -   filename : 1_INPUT/Python_Controllers/shakeModel.py
        classname : interface
