actuatorType: CableConstraint
mappingType: BarycentricMapping

modelActuator:

-   name: nord 
    range: 
        maxPull: 40
    actuator: 
        pullPoint: 0 10 30
    mechanicalObject:
        position : 0 97 45

-   name: ouest
    range: 
        maxPull: 40
    actuator: 
        pullPoint: -10 0 30
    mechanicalObject:
        position : -97 0 45

-   name: sud
    range: 
        maxPull: 40
    actuator: 
        pullPoint: 0 -10 30
    mechanicalObject:
        position : 0 -97 45

-   name: est
    range: 
        maxPull: 40
    actuator: 
        pullPoint: 10 0 30
    mechanicalObject:
        position : 97 0 45