ECSWBool: {perform: false, performMappedMatrix: false, prepare: true}
actuatorParam: {breathTime: 0, increment: 5, modulo: 10}
HyperReducedFEMForceField: {youngModulus: 450, poissonRatio: 0.45, nbTrainingSet: 200}
connectivityFileName: test.txt
gieFilename: DiamondWellConverged_HyperReducedFF_Quite_30_Gie.txt
gieFilename_subTopo: HyperReducedTriangleFEMForceField_Gie.txt
listActiveNodesFileName: listActiveNodesUnion.txt
modes: {addRigidBodyModes: false, modesFileName: blop.txt, pathTodir: 2_OUTPUT/2_Modes_Options/,
  tolerance: 0.001}
nbModes: 30
stateFile: {initState: true, nameStateFile: test, pathTodir: 2_OUTPUT/1_State_Files/}
weightsAndRID: {RIDFileName: RID_blop.txt, pathTodir: 2_OUTPUT/3_Reduced_Model/, tolerance: 0.05,
  weightsFileName: weights_blop.txt}
