robotParam:
    pathTodir: /home/felix/SOFA/plugin/ModelOrderReduction/examples/Mesh/
    nameRobotMesh: siliconeV0.vtu
    nameRobotStl: surface.stl
    nbModes: 30 #Number of modes wanted
    nbActuator: 4
    increment : 5

robotActuator: 
    -  
        type: CableConstraint
        name: nord
        pullPoint : "0 10 30"
        range: 
            maxPull : 40
    -
        type: CableConstraint
        name: ouest
        pullPoint: "-10 0 30"
        range: 
            maxPull : 40
    - 
        type: CableConstraint
        name: sud
        pullPoint: "0 -10 30"
        range: 
            maxPull : 40 
    -
        type: CableConstraint
        name: est
        pullPoint: "10 0 30"
        range: 
            maxPull : 40

other:
    verbose: False

####    First Step      ####
#
#   Launch SOFA scene and with the python script controller "shakeDiamondRobotNG" 
#   (activate the different actuator covering all the actuating possibilities)
#   and recover the different states of the fine meshed robot  

stateFile:
    pathTodir: /home/felix/SOFA/plugin/ModelOrderReduction/examples/State_Files/
    nameStateFile: myStateFile
    initState: True

############################
####    Second Step     ####
#
#   Execute python script "readStateFilesAndComputeModes"
#   which will from the previously generated states files 
#   produced the mode file describing a "lvl 1" reduced model

modes:
    pathTodir: /home/felix/SOFA/plugin/ModelOrderReduction/examples/modes_Options/
    modesFileName: blop.txt
    tolerance: 0.001
    addRigidBodyModes: false

############################
####    Third Step      ####
#
#   Launch another SOFA scene using the previously generated modes
#   and using the MOR component reduced it further

ECSWBool:
    prepare: 'false'
    perform: 'true'
    performMappedMatrix: 'false'

############################
####    Fourth Step     ####
#
#

gieFilename: DiamondWellConverged_HyperReducedFF_Quite_30_Gie.txt

weightsAndRID:
    pathTodir: /home/felix/SOFA/plugin/ModelOrderReduction/examples/ECSWdata_stored/
    RIDFileName: RID_blop.txt
    weightsFileName: weights_blop.txt
    tolerance: 0.05

############################
####    Fifth Step     ####
#
#

connectivityFilename: test.txt
listActiveNodesFileName: listActiveNodes.txt